// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace ManaFood.BDD.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class GerenciamentoDeUsuariosFeature : object, Xunit.IClassFixture<GerenciamentoDeUsuariosFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "User.feature"
#line hidden
        
        public GerenciamentoDeUsuariosFeature(GerenciamentoDeUsuariosFeature.FixtureData fixtureData, ManaFood_BDD_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-BR"), "Features", "Gerenciamento de Usuários", "  Como um sistema de gerenciamento de usuários\r\n  Eu quero criar, buscar, atualiz" +
                    "ar e deletar usuários\r\n  Para que os clientes possam se cadastrar e gerenciar su" +
                    "as contas", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Criar um usuário válido")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Criar um usuário válido")]
        public void CriarUmUsuarioValido()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Criar um usuário válido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 8
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
                TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table1.AddRow(new string[] {
                            "Email",
                            "teste.usuario@example.com"});
                table1.AddRow(new string[] {
                            "Nome",
                            "João da Silva"});
                table1.AddRow(new string[] {
                            "CPF",
                            "11144477735"});
                table1.AddRow(new string[] {
                            "Senha",
                            "SenhaForte@123"});
                table1.AddRow(new string[] {
                            "DataNasc",
                            "1990-05-15"});
                table1.AddRow(new string[] {
                            "TipoUser",
                            "1"});
#line 9
  testRunner.Given("que eu tenho os dados de um novo usuário válido", ((string)(null)), table1, "Dado ");
#line hidden
#line 17
  testRunner.When("eu solicito a criação do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 18
  testRunner.Then("o sistema deve criar o usuário com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 19
  testRunner.And("o usuário deve ter um ID gerado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 20
  testRunner.And("a senha deve estar criptografada", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 21
  testRunner.And("o email deve ser \"teste.usuario@example.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Não permitir criar usuário com email duplicado")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Não permitir criar usuário com email duplicado")]
        public void NaoPermitirCriarUsuarioComEmailDuplicado()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Não permitir criar usuário com email duplicado", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 23
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 24
  testRunner.Given("que já existe um usuário com email \"usuario.existente@example.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table2.AddRow(new string[] {
                            "Email",
                            "usuario.existente@example.com"});
                table2.AddRow(new string[] {
                            "Nome",
                            "Maria Santos"});
                table2.AddRow(new string[] {
                            "CPF",
                            "52998224725"});
                table2.AddRow(new string[] {
                            "Senha",
                            "OutraSenha@456"});
                table2.AddRow(new string[] {
                            "DataNasc",
                            "1995-08-20"});
                table2.AddRow(new string[] {
                            "TipoUser",
                            "1"});
#line 25
  testRunner.And("eu tento criar um novo usuário com os dados", ((string)(null)), table2, "E ");
#line hidden
#line 33
  testRunner.When("eu solicito a criação do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 34
  testRunner.Then("o sistema deve retornar um erro de email duplicado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 35
  testRunner.And("a mensagem deve conter \"já está vinculado a um usuário\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Não permitir criar usuário com CPF duplicado")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Não permitir criar usuário com CPF duplicado")]
        public void NaoPermitirCriarUsuarioComCPFDuplicado()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Não permitir criar usuário com CPF duplicado", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 37
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 38
  testRunner.Given("que já existe um usuário com CPF \"52998224725\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "Campo",
                            "Valor"});
                table3.AddRow(new string[] {
                            "Email",
                            "novo.usuario@example.com"});
                table3.AddRow(new string[] {
                            "Nome",
                            "Pedro Oliveira"});
                table3.AddRow(new string[] {
                            "CPF",
                            "52998224725"});
                table3.AddRow(new string[] {
                            "Senha",
                            "MinhaSenha@789"});
                table3.AddRow(new string[] {
                            "DataNasc",
                            "1988-12-10"});
                table3.AddRow(new string[] {
                            "TipoUser",
                            "2"});
#line 39
  testRunner.And("eu tento criar um novo usuário com os dados", ((string)(null)), table3, "E ");
#line hidden
#line 47
  testRunner.When("eu solicito a criação do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 48
  testRunner.Then("o sistema deve retornar um erro de CPF duplicado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 49
  testRunner.And("a mensagem deve conter \"já está vinculado a um usuário\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar usuário por ID")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Buscar usuário por ID")]
        public void BuscarUsuarioPorID()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar usuário por ID", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 51
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 52
  testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 53
  testRunner.When("eu busco o usuário por ID", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 54
  testRunner.Then("o sistema deve retornar os dados do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 55
  testRunner.And("o nome do usuário deve ser \"João da Silva\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 56
  testRunner.And("o email do usuário deve ser \"joao.silva@example.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar usuário por email")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Buscar usuário por email")]
        public void BuscarUsuarioPorEmail()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar usuário por email", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 58
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 59
  testRunner.Given("que existe um usuário com email \"maria.santos@example.com\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 60
  testRunner.When("eu busco o usuário por email", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 61
  testRunner.Then("o sistema deve retornar os dados do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 62
  testRunner.And("o nome do usuário deve ser \"Maria Santos\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Buscar usuário por CPF")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Buscar usuário por CPF")]
        public void BuscarUsuarioPorCPF()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Buscar usuário por CPF", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 64
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 65
  testRunner.Given("que existe um usuário com CPF \"55566677788\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 66
  testRunner.When("eu busco o usuário por CPF", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 67
  testRunner.Then("o sistema deve retornar os dados do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 68
  testRunner.And("o nome do usuário deve ser \"Carlos Pereira\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Listar todos os usuários")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Listar todos os usuários")]
        public void ListarTodosOsUsuarios()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Listar todos os usuários", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 70
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 71
  testRunner.Given("que existem 5 usuários cadastrados no sistema", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 72
  testRunner.When("eu solicito a listagem de todos os usuários", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 73
  testRunner.Then("o sistema deve retornar 5 usuários", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 74
  testRunner.And("todos devem ter ID, nome e email válidos", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Atualizar dados de um usuário")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Atualizar dados de um usuário")]
        public void AtualizarDadosDeUmUsuario()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Atualizar dados de um usuário", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 76
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 77
  testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 78
  testRunner.And("eu atualizo o nome para \"João da Silva Atualizado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
#line 79
  testRunner.When("eu solicito a atualização do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 80
  testRunner.Then("o sistema deve atualizar o usuário com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 81
  testRunner.And("o nome do usuário deve ser \"João da Silva Atualizado\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Deletar um usuário")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Deletar um usuário")]
        public void DeletarUmUsuario()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Deletar um usuário", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 83
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 84
  testRunner.Given("que existe um usuário com ID \"3fa85f64-5717-4562-b3fc-2c963f66afa6\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 85
  testRunner.When("eu solicito a exclusão do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 86
  testRunner.Then("o sistema deve deletar o usuário com sucesso", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar CPF inválido")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Validar CPF inválido")]
        public void ValidarCPFInvalido()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar CPF inválido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 88
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 89
  testRunner.Given("que eu tento criar um usuário com CPF inválido \"12345678901\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 90
  testRunner.When("eu solicito a criação do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 91
  testRunner.Then("o sistema deve retornar um erro de validação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 92
  testRunner.And("a mensagem deve indicar CPF inválido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar email inválido")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Validar email inválido")]
        public void ValidarEmailInvalido()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar email inválido", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 94
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 95
  testRunner.Given("que eu tento criar um usuário com email inválido \"emailinvalido\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 96
  testRunner.When("eu solicito a criação do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 97
  testRunner.Then("o sistema deve retornar um erro de validação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 98
  testRunner.And("a mensagem deve indicar email inválido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar senha fraca")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Validar senha fraca")]
        public void ValidarSenhaFraca()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar senha fraca", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 100
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 101
  testRunner.Given("que eu tento criar um usuário com senha fraca \"12\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 102
  testRunner.When("eu solicito a criação do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 103
  testRunner.Then("o sistema deve retornar um erro de validação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 104
  testRunner.And("a mensagem deve indicar senha fraca", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar data de nascimento futura")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Validar data de nascimento futura")]
        public void ValidarDataDeNascimentoFutura()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar data de nascimento futura", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 106
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 107
  testRunner.Given("que eu tento criar um usuário com data de nascimento futura \"2030-01-01\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 108
  testRunner.When("eu solicito a criação do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 109
  testRunner.Then("o sistema deve retornar um erro de validação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 110
  testRunner.And("a mensagem deve indicar data de nascimento inválida", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Validar usuário menor de idade")]
        [Xunit.TraitAttribute("FeatureTitle", "Gerenciamento de Usuários")]
        [Xunit.TraitAttribute("Description", "Validar usuário menor de idade")]
        public void ValidarUsuarioMenorDeIdade()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validar usuário menor de idade", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 112
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 113
  testRunner.Given("que eu tento criar um usuário com data de nascimento \"2020-01-01\"", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
#line 114
  testRunner.When("eu solicito a criação do usuário", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line hidden
#line 115
  testRunner.Then("o sistema deve retornar um erro de validação", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
#line 116
  testRunner.And("a mensagem deve indicar que o usuário deve ser maior de idade", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                GerenciamentoDeUsuariosFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                GerenciamentoDeUsuariosFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
